language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=Django==1.4
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=git+https://github.com/django/django.git@master

matrix:
  allow_failures:
    - env: DJANGO_VERSION=git+https://github.com/django/django.git@master

before_install:
 - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-dev gfortran

install:
  - pip install -q -U pip
  - pip install -q --use-mirrors $DJANGO_VERSION
  - pip install -q numpy --use-mirrors
  - pip install -q scipy --use-mirrors
  - pip install -q pandas --use-mirrors
  - pip install -q scikit-learn --use-mirrors
  - pip install -q patsy --use-mirrors
  - pip install -q statsmodels --use-mirrors
  - pip install -q python-coveralls --use-mirrors
  - pip install -q statsmodels --use-mirrors

script: coverage run runtests.py

notifications:
  email:
    - craig@eyesopen.com

after_success:
  - coveralls