language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=Django==1.4
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=git+https://github.com/django/django.git@stable/1.6.x

matrix:
  allow_failures:
    - env: DJANGO_VERSION=git+https://github.com/django/django.git@stable/1.6.x

before_install:
 - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-dev gfortran

install:
  - pip install -q --use-mirrors $DJANGO_VERSION
  - pip install -q numpy --use-mirrors
  - pip install -q scipy --use-mirrors
  - pip install -q matplotlib pandas scikit-learn patsy --use-mirrors
  - pip install -q statsmodels==0.5.0rc1 --use-mirrors
  - pip install -q python-coveralls --use-mirrors
  - python setup.py -q install

script: coverage run runtests.py

notifications:
  email:
    - craig@eyesopen.com

after_success:
  - coveralls