language: python

python:
  - 2.7

cache: apt

env:
  - DJANGO_VERSION=Django==1.4
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=git+https://github.com/django/django.git@master

matrix:
  allow_failures:
    - env: DJANGO_VERSION=git+https://github.com/django/django.git@master

before_install:
 - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-dev gfortran

install:
  - pip install -q -U pip
  - pip install -q $DJANGO_VERSION
  - pip install -q numpy
  - pip install -vvv scipy
  - pip install -r requirements.txt
#  - pip install -q pandas
#  - pip install -q scikit-learn patsy
#  - pip install -q statsmodels
#  - pip install -q python-coveralls django-analytical celery pytz

script: coverage run runtests.py

notifications:
  email:
    - craig@eyesopen.com

after_success:
  - coveralls