language: python

python:
  - 2.7

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=dev

matrix:
  allow_failures:
    - env: DJANGO=dev

before_install:
 - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-dev gfortran

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q numpy --use-mirrors
  - pip install -q scipy --use-mirrors
  - pip install -q matplotlib pandas scikit-learn patsy --use-mirrors
  - pip install -q statsmodels==0.5.0rc1 --use-mirrors
  - pip install -q python-coveralls
  - python setup.py -q install

script: coverage run runtests.py

notifications:
  email:
    - craig@eyesopen.com

after_success:
  - coveralls